### ISSUE TITLE
Link for cloud have duplicate https:// resulting in failure to open page

### ISSUE THREAD

**Issue by castortech** [ai-made-approachable/rivet-chat-api#15]
As described in title.

**Comment by ai-made-approachable** [comment]
Thanks for the info. I just do not manage to find the issue. Are you talking about the "Deploy on Railway" button and the link in the readme.md? Because they should be fine and also both work for me:

```## Installation
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/XjMVyQ?referralCode=Bc2Iiw)

Click the button above or go to https://railway.app/template/XjMVyQ?referralCode=Bc2Iiw and click "Deploy Now"```

**Comment by castortech** [comment]
![image](https://github.com/ai-made-approachable/rivet-chat-api/assets/85858/9c627b26-1801-4600-8c38-225425fdca1b)

**Comment by ai-made-approachable** [comment]
Ah right. It is fixed.
Thank you!
